// Generated by view binder compiler. Do not edit!
package com.example.stal_new.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.FrameLayout;
import android.widget.ImageView;
import android.widget.SearchView;
import android.widget.TextView;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.appcompat.widget.AppCompatButton;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.example.stal_new.R;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;

public final class FragmentHomeBinding implements ViewBinding {
  @NonNull
  private final FrameLayout rootView;

  @NonNull
  public final SearchView SearchViewHome;

  @NonNull
  public final AppCompatButton buttoFasad;

  @NonNull
  public final AppCompatButton buttoKrovlya;

  @NonNull
  public final AppCompatButton buttoMettaloprrokat;

  @NonNull
  public final AppCompatButton buttoOgrazdenia;

  @NonNull
  public final AppCompatButton buttoPodrobnee;

  @NonNull
  public final AppCompatButton buttoPrrofilOC;

  @NonNull
  public final AppCompatButton buttoSkidki;

  @NonNull
  public final ImageView imageView;

  @NonNull
  public final ImageView imageView20;

  @NonNull
  public final ImageView imageView200;

  @NonNull
  public final ImageView imageView2000;

  @NonNull
  public final ImageView imageView21;

  @NonNull
  public final ImageView imageView4;

  @NonNull
  public final TextView textView;

  @NonNull
  public final TextView textView13;

  @NonNull
  public final TextView textView14;

  @NonNull
  public final TextView textView15;

  @NonNull
  public final TextView textView2;

  @NonNull
  public final TextView textView6;

  @NonNull
  public final TextView textView60;

  @NonNull
  public final TextView textView600;

  @NonNull
  public final TextView textView7;

  @NonNull
  public final TextView textView70;

  @NonNull
  public final TextView textView700;

  @NonNull
  public final TextView textViewBalka;

  @NonNull
  public final TextView textViewBalkaFour;

  @NonNull
  public final TextView textViewBalkaTri;

  private FragmentHomeBinding(@NonNull FrameLayout rootView, @NonNull SearchView SearchViewHome,
      @NonNull AppCompatButton buttoFasad, @NonNull AppCompatButton buttoKrovlya,
      @NonNull AppCompatButton buttoMettaloprrokat, @NonNull AppCompatButton buttoOgrazdenia,
      @NonNull AppCompatButton buttoPodrobnee, @NonNull AppCompatButton buttoPrrofilOC,
      @NonNull AppCompatButton buttoSkidki, @NonNull ImageView imageView,
      @NonNull ImageView imageView20, @NonNull ImageView imageView200,
      @NonNull ImageView imageView2000, @NonNull ImageView imageView21,
      @NonNull ImageView imageView4, @NonNull TextView textView, @NonNull TextView textView13,
      @NonNull TextView textView14, @NonNull TextView textView15, @NonNull TextView textView2,
      @NonNull TextView textView6, @NonNull TextView textView60, @NonNull TextView textView600,
      @NonNull TextView textView7, @NonNull TextView textView70, @NonNull TextView textView700,
      @NonNull TextView textViewBalka, @NonNull TextView textViewBalkaFour,
      @NonNull TextView textViewBalkaTri) {
    this.rootView = rootView;
    this.SearchViewHome = SearchViewHome;
    this.buttoFasad = buttoFasad;
    this.buttoKrovlya = buttoKrovlya;
    this.buttoMettaloprrokat = buttoMettaloprrokat;
    this.buttoOgrazdenia = buttoOgrazdenia;
    this.buttoPodrobnee = buttoPodrobnee;
    this.buttoPrrofilOC = buttoPrrofilOC;
    this.buttoSkidki = buttoSkidki;
    this.imageView = imageView;
    this.imageView20 = imageView20;
    this.imageView200 = imageView200;
    this.imageView2000 = imageView2000;
    this.imageView21 = imageView21;
    this.imageView4 = imageView4;
    this.textView = textView;
    this.textView13 = textView13;
    this.textView14 = textView14;
    this.textView15 = textView15;
    this.textView2 = textView2;
    this.textView6 = textView6;
    this.textView60 = textView60;
    this.textView600 = textView600;
    this.textView7 = textView7;
    this.textView70 = textView70;
    this.textView700 = textView700;
    this.textViewBalka = textViewBalka;
    this.textViewBalkaFour = textViewBalkaFour;
    this.textViewBalkaTri = textViewBalkaTri;
  }

  @Override
  @NonNull
  public FrameLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static FragmentHomeBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static FragmentHomeBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.fragment_home, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static FragmentHomeBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.SearchView_home;
      SearchView SearchViewHome = ViewBindings.findChildViewById(rootView, id);
      if (SearchViewHome == null) {
        break missingId;
      }

      id = R.id.buttoFasad;
      AppCompatButton buttoFasad = ViewBindings.findChildViewById(rootView, id);
      if (buttoFasad == null) {
        break missingId;
      }

      id = R.id.buttoKrovlya;
      AppCompatButton buttoKrovlya = ViewBindings.findChildViewById(rootView, id);
      if (buttoKrovlya == null) {
        break missingId;
      }

      id = R.id.buttoMettaloprrokat;
      AppCompatButton buttoMettaloprrokat = ViewBindings.findChildViewById(rootView, id);
      if (buttoMettaloprrokat == null) {
        break missingId;
      }

      id = R.id.buttoOgrazdenia;
      AppCompatButton buttoOgrazdenia = ViewBindings.findChildViewById(rootView, id);
      if (buttoOgrazdenia == null) {
        break missingId;
      }

      id = R.id.buttoPodrobnee;
      AppCompatButton buttoPodrobnee = ViewBindings.findChildViewById(rootView, id);
      if (buttoPodrobnee == null) {
        break missingId;
      }

      id = R.id.buttoPrrofilOC;
      AppCompatButton buttoPrrofilOC = ViewBindings.findChildViewById(rootView, id);
      if (buttoPrrofilOC == null) {
        break missingId;
      }

      id = R.id.buttoSkidki;
      AppCompatButton buttoSkidki = ViewBindings.findChildViewById(rootView, id);
      if (buttoSkidki == null) {
        break missingId;
      }

      id = R.id.imageView;
      ImageView imageView = ViewBindings.findChildViewById(rootView, id);
      if (imageView == null) {
        break missingId;
      }

      id = R.id.imageView20;
      ImageView imageView20 = ViewBindings.findChildViewById(rootView, id);
      if (imageView20 == null) {
        break missingId;
      }

      id = R.id.imageView200;
      ImageView imageView200 = ViewBindings.findChildViewById(rootView, id);
      if (imageView200 == null) {
        break missingId;
      }

      id = R.id.imageView2000;
      ImageView imageView2000 = ViewBindings.findChildViewById(rootView, id);
      if (imageView2000 == null) {
        break missingId;
      }

      id = R.id.imageView21;
      ImageView imageView21 = ViewBindings.findChildViewById(rootView, id);
      if (imageView21 == null) {
        break missingId;
      }

      id = R.id.imageView4;
      ImageView imageView4 = ViewBindings.findChildViewById(rootView, id);
      if (imageView4 == null) {
        break missingId;
      }

      id = R.id.textView;
      TextView textView = ViewBindings.findChildViewById(rootView, id);
      if (textView == null) {
        break missingId;
      }

      id = R.id.textView13;
      TextView textView13 = ViewBindings.findChildViewById(rootView, id);
      if (textView13 == null) {
        break missingId;
      }

      id = R.id.textView14;
      TextView textView14 = ViewBindings.findChildViewById(rootView, id);
      if (textView14 == null) {
        break missingId;
      }

      id = R.id.textView15;
      TextView textView15 = ViewBindings.findChildViewById(rootView, id);
      if (textView15 == null) {
        break missingId;
      }

      id = R.id.textView2;
      TextView textView2 = ViewBindings.findChildViewById(rootView, id);
      if (textView2 == null) {
        break missingId;
      }

      id = R.id.textView6;
      TextView textView6 = ViewBindings.findChildViewById(rootView, id);
      if (textView6 == null) {
        break missingId;
      }

      id = R.id.textView60;
      TextView textView60 = ViewBindings.findChildViewById(rootView, id);
      if (textView60 == null) {
        break missingId;
      }

      id = R.id.textView600;
      TextView textView600 = ViewBindings.findChildViewById(rootView, id);
      if (textView600 == null) {
        break missingId;
      }

      id = R.id.textView7;
      TextView textView7 = ViewBindings.findChildViewById(rootView, id);
      if (textView7 == null) {
        break missingId;
      }

      id = R.id.textView70;
      TextView textView70 = ViewBindings.findChildViewById(rootView, id);
      if (textView70 == null) {
        break missingId;
      }

      id = R.id.textView700;
      TextView textView700 = ViewBindings.findChildViewById(rootView, id);
      if (textView700 == null) {
        break missingId;
      }

      id = R.id.textViewBalka;
      TextView textViewBalka = ViewBindings.findChildViewById(rootView, id);
      if (textViewBalka == null) {
        break missingId;
      }

      id = R.id.textViewBalkaFour;
      TextView textViewBalkaFour = ViewBindings.findChildViewById(rootView, id);
      if (textViewBalkaFour == null) {
        break missingId;
      }

      id = R.id.textViewBalkaTri;
      TextView textViewBalkaTri = ViewBindings.findChildViewById(rootView, id);
      if (textViewBalkaTri == null) {
        break missingId;
      }

      return new FragmentHomeBinding((FrameLayout) rootView, SearchViewHome, buttoFasad,
          buttoKrovlya, buttoMettaloprrokat, buttoOgrazdenia, buttoPodrobnee, buttoPrrofilOC,
          buttoSkidki, imageView, imageView20, imageView200, imageView2000, imageView21, imageView4,
          textView, textView13, textView14, textView15, textView2, textView6, textView60,
          textView600, textView7, textView70, textView700, textViewBalka, textViewBalkaFour,
          textViewBalkaTri);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
